[wokwi]
version = 1
firmware = ".pio/build/esp32dev/firmware.elf"
elf = ".pio/build/esp32dev/firmware.elf"
gdbServerPort = 3333
gdbPath = "C:/Users/quinn/.platformio/packages/toolchain-xtensa-esp32/bin/xtensa-esp32-elf-gdb.exe"